<?xml version="1.0" encoding="ISO-8859-1" ?>
<!--banco-de-dados.sql
Generated 2023-11-07 22:44
-->
<database>
<name>modelagem</name>
<create>1</create>
<table>
<name>marca</name>
<declaration>
<field>
<name>id_marca</name>
<type>INTEGER</type>
<default></default>
<notnull>1</notnull>
</field>
<field>
<name>nome_marca</name>
<type>TEXT</type>
<default></default>
<notnull>0</notnull>
</field>
<index>
<name>PRIMARY</name>
<unique>1</unique>
<field>
<name>id_marca</name>
</field>
</index>
</declaration>
<initialization>
</initialization>
</table>
<table>
<name>modelo</name>
<declaration>
<field>
<name>id_modelo</name>
<type>INTEGER</type>
<default></default>
<notnull>1</notnull>
</field>
<field>
<name>marca_id_marca</name>
<type>INTEGER</type>
<default></default>
<notnull>1</notnull>
</field>
<field>
<name>nome_modelo</name>
<type>TEXT</type>
<default></default>
<notnull>0</notnull>
</field>
<field>
<name>cor_modelo</name>
<type>TEXT</type>
<default></default>
<notnull>0</notnull>
</field>
<field>
<name>ano_modelo</name>
<type>INTEGER</type>
<default></default>
<notnull>0</notnull>
</field>
<field>
<name>placa_modelo</name>
<type>TEXT</type>
<default></default>
<notnull>0</notnull>
</field>
<index>
<name>PRIMARY</name>
<unique>1</unique>
<field>
<name>id_modelo</name>
</field>
</index>
<index>
<name>modelo_FKIndex1</name>
<unique>0</unique>
<field>
<name>marca_id_marca</name>
</field>
</index>
</declaration>
<initialization>
</initialization>
</table>
</database>
